questions = {
    "childhood": "Where did you grow up, and what was your childhood like?",
    "memories": "What are some of your favorite memories from childhood?",
    "role_models": "Did you have any significant role models growing up? Who were they?",
    "education_experience": "What was your experience like in school? Did you enjoy it?",
    "passions": "What subjects or activities were you most passionate about in school?",
    "further_education": "Did you attend college or pursue any further education? What did you study?",
    "first_job": "What was your first job, and what did you learn from it?",
    "career_choice": "How did you choose your current career path?",
    "job_aspects": "What are some of the most rewarding or challenging aspects of your job?",
    "hobbies": "What are your hobbies or interests outside of work?",
    "free_time": "How do you like to spend your weekends or free time?",
    "pets": "Do you have any pets? If so, tell me about them.",
    "important_people": "Who are the most important people in your life, and how did you meet them?",
    "friendship_qualities": "What qualities do you value most in friendships or relationships?",
    "family_influence": "How has your family influenced who you are today?",
    "life_events": "What are some major life events that have shaped you?",
    "travel_impact": "Have you traveled to any places that had a significant impact on you?",
    "challenges": "What challenges have you faced in life, and how did you overcome them?",
    "core_values": "What are your core values or beliefs that guide your life?",
    "success_definition": "How do you define success and happiness for yourself?",
    "passions_causes": "What causes or issues are you passionate about?",
    "future_goals": "What goals do you have for the future, both personally and professionally?",
    "life_change": "If you could change one thing about your life, what would it be?",
    "legacy": "What legacy do you hope to leave behind?",
    "advice": "Looking back, what advice would you give your younger self?",
    "pride": "What are you most proud of in your life so far?",
    "change": "How do you think you've changed over the years?"
}
